config/routes.rb
Ealingecho::Application.routes.draw do
  resources :assignments

  resources :echoforms

  resources :requests

  devise_for :users
  devise_for :requests

  resources :patients

  root :to => "requests#index"

end

app/models/assignment.rb
class Assignment < ActiveRecord::Base
  attr_accessible :request_id, :user_id

  belongs_to :user
  belongs_to :request




end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
  # GET /assignments
  # GET /assignments.json
  def index
    @assignments = Assignment.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assignments }
    end
  end

  # GET /assignments/1
  # GET /assignments/1.json
  def show
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/new
  # GET /assignments/new.json
  def new
    @assignment = Assignment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assignment }
    end
  end

  # GET /assignments/1/edit
  def edit
    @assignment = Assignment.find(params[:id])
  end

  # POST /assignments
  # POST /assignments.json
  def create
    #@assignment = Assignment.new(params[:assignment])
     @assignment = current_user.assignments.create(request_id: params[:request_id]) unless @assignment
    #respond_to do |format|
      #if @assignment.save
       # format.html { redirect_to @assignment, notice: 'Assignment was successfully created.' }
       # format.json { render json: @assignment, status: :created, location: @assignment }
      #else
       # format.html { render action: "new" }
       # format.json { render json: @assignment.errors, status: :unprocessable_entity }
   redirect_to assignments_path
  end

  # PUT /assignments/1
  # PUT /assignments/1.json
  def update
    @assignment = Assignment.find(params[:id])

    respond_to do |format|
      if @assignment.update_attributes(params[:assignment])
        format.html { redirect_to @assignment, notice: 'Assignment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assignment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assignments/1
  # DELETE /assignments/1.json
  def destroy
    @assignment = Assignment.find(params[:id])
    @assignment.destroy

    respond_to do |format|
      format.html { redirect_to assignments_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/views/assignments/_form.html.haml
= simple_form_for(@assignment) do |f|
  = f.error_notification

  .form-inputs
    = f.association :user, :label_method => :email
    = f.association :request, :label_method => :patient_id

  .form-actions
    = f.button :submit

app/views/assignments/edit.html.haml
%h1 Editing assignment

= render 'form'

= link_to 'Show', @assignment
\|
= link_to 'Back', assignments_path

app/views/assignments/index.html.haml
%h1 Listing assignments

%table.table.table-bordered.table-striped.table-hover
  %tr
    %th Ultrasonographer
    %th First Name
    %th Last Name
    %th DOB
    %th MRN

  - @assignments.each do |assignment|
    %tr
      /
      %td= best_in_place assignment, :user_id, :type => :select, :collection => User::list_users
      /%td= assignment.request_id
      %td= assignment.request.patient.first_name
      %td= assignment.request.patient.last_name
      %td= assignment.request.patient.dob
      %td= assignment.request.patient.mrn
      %td= link_to 'Show', assignment
      %td= link_to 'Edit', edit_assignment_path(assignment)
      %td= link_to 'Destroy', assignment, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Assignment', new_assignment_path

app/views/assignments/new.html.haml
%h1 New assignment

= render 'form'

= link_to 'Back', assignments_path

app/views/assignments/show.html.haml
%p#notice= notice

%p
  %b User:
  = @assignment.user_id
%p
  %b Request:
  = @assignment.request_id

= link_to 'Edit', edit_assignment_path(@assignment)
\|
= link_to 'Back', assignments_path