config/routes.rb
Ealingecho::Application.routes.draw do
  resources :assignments

  resources :echoforms

  resources :requests

  devise_for :users
  devise_for :requests

  resources :patients

  root :to => "requests#index"

end

app/models/request.rb
class Request < ActiveRecord::Base
  attr_accessible :priority, :approved

  belongs_to :echoform
  belongs_to :patient
  accepts_nested_attributes_for :echoform
  has_many :assignments
  has_many :users, through: :assignments
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  # GET /requests
  # GET /requests.json
 before_filter :authenticate_user!
  def index
    @requests = Request.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @requests }
    end
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
    @request = Request.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/new
  # GET /requests/new.json
  def new
    @request = Request.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @request }
    end
  end

  # GET /requests/1/edit
  def edit
    @request = Request.find(params[:id])
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(params[:request])

    respond_to do |format|
      if @request.save
        format.html { redirect_to @request, notice: 'Request was successfully created.' }
        format.json { render json: @request, status: :created, location: @request }
      else
        format.html { render action: "new" }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /requests/1
  # PUT /requests/1.json
  def update
    @request = Request.find(params[:id])

    respond_to do |format|
      if @request.update_attributes(params[:request])
        #format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        #format.json { head :no_content }
        format.json { respond_with_bip(@request) }
      else
        format.html { render action: "edit" }
        #format.json { render json: @request.errors, status: :unprocessable_entity }
        format.json { respond_with_bip(@request) }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request = Request.find(params[:id])
    @request.destroy

    respond_to do |format|
      format.html { redirect_to requests_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.haml
= simple_form_for(@request) do |f|
  = f.error_notification

  .form-inputs

  .form-actions
    = f.button :submit

app/views/requests/edit.html.haml
%h1 Editing request

= render 'form'

= link_to 'Show', @request
\|
= link_to 'Back', requests_path

app/views/requests/index.html.haml
%h1 Listing requests

%table.table.table-bordered.table-striped.table-hover
  %tr
    %th First Name
    %th Last Name
    %th DOB
    %th MRN
    %th sex
    %th Clinical details
    %th ECG Changes
    %th Ward
    %th Consultant
    %th Echo Type
    %th Approved?
    %th Priority

  - @requests.each do |request|
   
    %tr
      %td= request.patient.first_name
      %td= request.patient.last_name
      %td= request.patient.dob
      %td= request.patient.mrn
      %td= request.patient.sex
      %td= request.echoform.clinical_details
      %td= request.echoform.ecg_changes
      %td= request.echoform.ward
      %td= request.echoform.consultant
      %td= request.echoform.echo_type


      
      /%td= request.approved
      %td= best_in_place request, :approved, :type => :checkbox, :collection => ["Yes", "No"]
      %td= best_in_place request, :priority, :type => :select, :collection => [[1, "1"], [2, "1"], [3, "3"], [4, "4"]] 
      

  
      %td= link_to 'Show', request
      %td= link_to 'Edit', edit_request_path(request)
      %td= link_to 'Destroy', request, :method => :delete, :data => { :confirm => 'Are you sure?' } 
      %td= link_to 'assign', assignments_path(request_id: request.id), method: :post, :class => 'btn btn-primary'
%br

= link_to 'New Request', new_request_path

app/views/requests/new.html.haml
%h1 New request

= render 'form'

= link_to 'Back', requests_path

app/views/requests/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_request_path(@request)
\|
= link_to 'Back', requests_path