config/routes.rb
Ealingecho::Application.routes.draw do
  resources :assignments

  resources :echoforms

  resources :requests

  devise_for :users
  devise_for :requests

  resources :patients

  root :to => "requests#index"

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :mrn, :dob, :sex, :echoforms_attributes
  	
  validates_format_of :mrn, :with => /\A[E]{1}[0-9]{8}\z/, :message => "not a valid E number"
  

  has_many :requests
  has_many :echoforms, through: :requests
  accepts_nested_attributes_for :echoforms
  accepts_nested_attributes_for :requests
  
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @patients }
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/new
  # GET /patients/new.json
  def new
    @patient = Patient.new
    @patient.echoforms.build


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @patient }
    end
  end

  # GET /patients/1/edit
  def edit
    @patient = Patient.find(params[:id])
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(params[:patient])

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render json: @patient, status: :created, location: @patient }
      else
        format.html { render action: "new" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /patients/1
  # PUT /patients/1.json
  def update
    @patient = Patient.find(params[:id])

    respond_to do |format|
      if @patient.update_attributes(params[:patient])
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient = Patient.find(params[:id])
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.haml
= simple_form_for (@patient) do |f|
  = f.error_notification

  .form-inputs
    = f.input :first_name, label: "First Name"
    = f.input :last_name, label: "Last Name" 
    = f.input :dob,  label: "DOB"
    = f.input :mrn,  label: "MRN", hint: 'Please enter the hospital number starting with E'
    = f.input :sex,  label: "SEX"

    = f.simple_fields_for :echoforms do |p|
      
      = p.input :clinical_details
      = p.input :consultant
      = p.input :doctor
      = p.input :ecg_changes
      = p.input :echo_type, as: :check_boxes, collection: ["ventricular function", "regional wall motion", "valve function", "suspected endocarditis", "suspected /confirmed PE"]
      = p.input :ward, collection: ["4S", "5S", "5N", "6N", "7S", "7N", "8S", "8N", "9S", "9N"], prompt: "Select ward"
  .form-actions
    = f.button :submit

app/views/patients/edit.html.haml
%h1 Editing patient

= render 'form'

= link_to 'Show', @patient
\|
= link_to 'Back', patients_path

app/views/patients/index.html.haml
%h1 Listing patients

%table.table.table-bordered.table-striped.table-hover
  %tr
    %th first name
    %th last name
    %th DOB
    %th MRN
    %th SEX
    %th Show
    %th Edit
    %th Delete


  - @patients.each do |patient|
    %tr
      %td= patient.first_name
      %td= patient.last_name
      %td= patient.dob
      %td= patient.mrn
      %td= patient.sex
      %td= link_to 'Show', patient
      %td= link_to 'Edit', edit_patient_path(patient)
      %td= link_to 'Destroy', patient, :method => :delete, :data => { :confirm => 'Are you sure?' }
      

%br

= link_to 'New Patient', new_patient_path

app/views/patients/new.html.haml
%h1 New patient

= render 'form'

= link_to 'Back', patients_path

app/views/patients/show.html.haml
%p#notice= notice


- @patient.requests.each do |request|
  %td= request.echoform.clinical_details


= link_to 'Edit', edit_patient_path(@patient)
\|
= link_to 'Back', patients_path