config/routes.rb
Ealingecho::Application.routes.draw do
  resources :assignments

  resources :echoforms

  resources :requests

  devise_for :users
  devise_for :requests

  resources :patients

  root :to => "requests#index"

end

app/controllers/echoforms_controller.rb
class EchoformsController < ApplicationController
  # GET /echoforms
  # GET /echoforms.json
  def index
    @echoforms = Echoform.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @echoforms }
    end
  end

  # GET /echoforms/1
  # GET /echoforms/1.json
  def show
    @echoform = Echoform.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @echoform }
    end
  end

  # GET /echoforms/new
  # GET /echoforms/new.json
  def new
    @echoform = Echoform.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @echoform }
    end
  end

  # GET /echoforms/1/edit
  def edit
    @echoform = Echoform.find(params[:id])
  end

  # POST /echoforms
  # POST /echoforms.json
  def create
    @echoform = Echoform.new(params[:echoform])

    respond_to do |format|
      if @echoform.save
        format.html { redirect_to @echoform, notice: 'Echoform was successfully created.' }
        format.json { render json: @echoform, status: :created, location: @echoform }
      else
        format.html { render action: "new" }
        format.json { render json: @echoform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /echoforms/1
  # PUT /echoforms/1.json
  def update
    @echoform = Echoform.find(params[:id])

    respond_to do |format|
      if @echoform.update_attributes(params[:echoform])
        format.html { redirect_to @echoform, notice: 'Echoform was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @echoform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /echoforms/1
  # DELETE /echoforms/1.json
  def destroy
    @echoform = Echoform.find(params[:id])
    @echoform.destroy

    respond_to do |format|
      format.html { redirect_to echoforms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/echoforms_helper.rb
module EchoformsHelper
end

app/views/echoforms/_form.html.haml
= simple_form_for(@echoform) do |f|
  = f.error_notification

  .form-inputs
    = f.input :clinical_details
    = f.input :ecg_changes
    = f.input :echo_type
    = f.input :ward
    = f.input :doctor
    = f.input :consultant

    = f.association :patients, :label_method => :last_name

  .form-actions
    = f.button :submit

app/views/echoforms/edit.html.haml
%h1 Editing echoform

= render 'form'

= link_to 'Show', @echoform
\|
= link_to 'Back', echoforms_path

app/views/echoforms/index.html.haml
%h1 Listing echoforms

%table
  %tr
    %th Clinical details
    %th Ecg changes
    %th Echo type
    %th Ward
    %th Doctor
    %th Consultant
    %th
    %th
    %th

  - @echoforms.each do |echoform|
    %tr
      
      %td= echoform.clinical_details
      %td= echoform.ecg_changes
      %td= echoform.echo_type
      %td= echoform.ward
      %td= echoform.doctor
      %td= echoform.consultant
      %td= link_to 'Show', echoform
      %td= link_to 'Edit', edit_echoform_path(echoform)
      %td= link_to 'Destroy', echoform, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Echoform', new_echoform_path

app/views/echoforms/new.html.haml
%h1 New echoform

= render 'form'

= link_to 'Back', echoforms_path

app/views/echoforms/show.html.haml
%p#notice= notice

%p
  %b Clinical details:
  = @echoform.clinical_details
%p
  %b Ecg changes:
  = @echoform.ecg_changes
%p
  %b Echo type:
  = @echoform.echo_type
%p
  %b Ward:
  = @echoform.ward
%p
  %b Doctor:
  = @echoform.doctor
%p
  %b Consultant:
  = @echoform.consultant

= link_to 'Edit', edit_echoform_path(@echoform)
\|
= link_to 'Back', echoforms_path